#!/bin/sh
#
# Starts gomd
#

CONFIG=/config/gomd.properties
if [ ! -f $CONFIG ]; then
  CONFIG=/etc/gomd.properties
fi

start() {
  echo -n "Starting gomd: "
  start-stop-daemon -S -q -p /var/run/gomd.pid \
    --exec /usr/bin/gomd -- $CONFIG
  [ $? == 0 ] && echo "OK" || echo "FAIL"
}

stop() {
  echo -n "Stopping gomd: "
  start-stop-daemon -K -q -p /var/run/gomd.pid
  [ $? == 0 ] && echo "OK" || echo "FAIL"
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?
